---
- name: setting database server
  hosts: db01

  user: vagrant
  become: yes
  vars_files:
    - vars/main.yml
  vars:
    - dbname: "db01"
    - dbusername: "root"
    - dbpassword: "root"
  roles:
    - default-so-settings
    - role: geerlingguy.mysql

